on:
  issue_comment:
    types: [created]
jobs:
  regression_testing_job:
    if: (github.event.comment.body == 'run') || startsWith(github.event.comment.body, 'run with checking out ') || startsWith(github.event.comment.body, 'run with pr ')
    runs-on: ubuntu-latest
    name: a job for regression testing
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install
      - run: node ./index.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
